### ISSUE TITLE
Page count in Articles and Notes sections

### ISSUE THREAD

**Issue by bpierre** [lesintegristes/lesintegristes-theme#38] opened 2012-10-02 16:53 UTC
The current page should be displayed in `<title>` and `<h1>`.

http://www.lesintegristes.net/articles/page/2/
http://www.lesintegristes.net/notes/page/2/

**Comment by welovewebdesign** [comment] 2012-10-06 19:12
Duplicate of #39

**Closed as completed by welovewebdesign** 2012-10-06 19:12 UTC
Labels: bug, todo
